on:
  push:
    branches:
      - master
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'custom_release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
