on:
  push:
    branches:
      - master
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@master
      - name: Shared Content
        id: shared_content
        run: |
          GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-8)
          EPOCH=$(date +'%s')
          DATE=$(date)
          echo "::set-output name=github_sha_short::$GITHUB_SHA_SHORT"
          echo "::set-output name=epoch::$EPOCH"
          echo "::set-output name=date::$DATE"
          echo "...."
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.shared_content.outputs.epoch }}
          release_name: Release - ${{ steps.shared_content.outputs.github_sha_short }}
          body: Release - ${{ steps.shared_content.outputs.date }}
          draft: false
          prerelease: false
