name : release creation action
on:
  push:
    branches:
      - main      
jobs:
  zip_creation_and_create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Installation of inspec and Creation of zip for release
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          export CHEF_LICENSE="accept"
          inspec -v
          for each_role_dir in $(ls | grep coupa)
          do
             echo "${each_role_dir}"
             inspec archive ./$each_role_dir  --zip --output=./"${each_role_dir}".zip
          done
          ls
      - name: Bump version and push tag
        id: bump_version_and_push_tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
      # - uses: fregante/release-with-changelog@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump_version_and_push_tag.outputs.new_tag }}   #steps.bump_version_and_push_tag.outputs.new_tag github.ref
          release_name: Release ${{ steps.bump_version_and_push_tag.outputs.new_tag }}
          body: |
            Release ${{ steps.bump_version_and_push_tag.outputs.new_tag }}
          draft: false
          prerelease: false

      - name : Printing create release output
        run:
             echo " Create release outputs = ${{steps.create_release.outputs.upload_url}}"
             echo "${{steps.create_release.outputs.html_url}}"
             echo "${{steps.create_release.outputs.id}}"
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path:  ./*.zip
