name : Trial action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Printing
        run: |
          echo "Hello World!!"

          ls -alh
          zip -r coupa-app.zip coupa-app
          echo "Coupa-app dir zipped"
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: './coupa-app'
          filename: 'coupa_app_release.zip'
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: './coupa-db'
          filename: 'coupa-db_release.zip'

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: coupa-db_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "release.zip"
      #     token: ${{ secrets.GITHUB_TOKEN }}
