name : Trial action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Printing
        run: |
          echo "Hello World!!"

          ls -alh
          zip -r coupa-app.zip coupa-app
          echo "Coupa-app dir zipped"
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          directory: './coupa-app'
          filename: 'release.zip'

          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
