name : Trial action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Printing
        run: |
          echo "Hello World!!"
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          export CHEF_LICENSE="accept"
          inspec -v
          for each_role_dir in $(ls | grep coupa)
          do
             echo "${each_role_dir}"
             inspec archive ./$each_role_dir  --zip --output=./"${each_role_dir}"_release.zip
          done
