name : Trial action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Printing
        run: |
          echo "Hello World!!"
          cd coupa-app
          ls -alh
        
