name : Trial action
on:
  push:
    branches:
      master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: |
          echo "Hello World!!"
          
        
